name: mirror

on:
  repository_dispatch:
    types: [mirror]

jobs:

  mirror:

    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
    - uses: actions/checkout@v3

    - name: clone
      run: |
        while ! git clone --mirror https://github.com/sbcl/sbcl.git sbcl; do
          sleep 5
        done
        cd sbcl
        git remote set-url origin https://git.code.sf.net/p/sbcl/sbcl

      working-directory: /tmp

    - name: fetch
      run: |
        while ! git fetch --prune; do
          sleep 5
        done

      working-directory: /tmp/sbcl

    - name: push
      run: |
        cd /tmp/sbcl
        git push --mirror https://sbcl:${{ secrets.MIRRORPAT }}@github.com/sbcl/sbcl.git

