name: mirror

on:
  repository_dispatch:
    types: [mirror]

jobs:

  mirror:

    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
    - uses: actions/checkout@v3

    - name: pull
      run: |
        while ! git clone --mirror https://git.code.sf.net/p/sbcl/sbcl sbcl; do
          sleep 5
        done

      working-directory: /tmp

    - name: push
      run: |
        cd /tmp/sbcl
        git push --mirror https://sbcl:${{ secrets.MIRRORPAT }}@github.com/sbcl/sbcl.git

